spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc9th
    username: root
    password: root1234!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql



