spring:
  application:
    name: devpath-backend
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      region:
        static: ap-southeast-2
      s3:
        bucket: teami-intro-bucket
  profiles:
    active: dev
